name: Test Submodule Cloning
on:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout recursively
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true

  submodule:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Clone submodule
      run: git submodule update --init llvm-project

  clone:
    name: Independent clone
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Clone repo
      run: git clone https://github.com/llvm/llvm-project.git llvm-project-2

  recursive:
    name: Recursive clone
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      run: git clone --recursive https://github.com/dime10/cloning-test.git

  actions:
    name: Actions clone
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Clone repo
      uses: actions/checkout@v3
      with:
        repository: llvm/llvm-project
        ref: 4821508d4db75a535d02b8938f81fac6de66cc26
        path: llvm-project-2

  shallow:
    name: Shallow clone
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Clone repo
      run: |
        mkdir llvm-project-2 && cd llvm-project-2
        git init
        git remote add origin https://github.com/llvm/llvm-project.git
        git fetch --depth 1 origin 4821508d4db75a535d02b8938f81fac6de66cc26
        git checkout FETCH_HEAD
